status = [
  "buildkite/haskell-dot-nix",
  "ci/hydra:Cardano:haskell-nix:required",
]
timeout_sec = 7200
required_approvals = 1
block_labels = [ "WIP", "DO NOT MERGE" ]
delete_merged_branches = true
