# Generated by .github/workflows/upload-artifacts-sh.yml for nix-tools-sh-0.2.2.
#
# The stable-haskell nix-tools pin, built from ./nix-tools-sh against the
# stable-haskell Cabal fork (3.17).  Separate from ./nix-tools-static.nix on
# purpose: these tools must NOT become the default for the existing GHC
# versions.  Opt in per project with haskell-nix.nix-tools-unchecked-sh; see
# overlays/default.nix.
pkgs: let baseurl = "https://github.com/input-output-hk/haskell.nix/releases/download/nix-tools-sh-0.2.2/"; in {
  aarch64-darwin = pkgs.fetchurl { 
     name = "aarch64-darwin-nix-tools-static-sh";
     url = "${baseurl}aarch64-darwin-nix-tools-static-sh.zip";
     sha256 = "sha256-HcZXxTvTZ/p6qfqOqUUF6u6q68znujvziydAVCbPHNk=";
  };
  x86_64-darwin = pkgs.fetchurl { 
     name = "x86_64-darwin-nix-tools-static-sh";
     url = "${baseurl}x86_64-darwin-nix-tools-static-sh.zip";
     sha256 = "sha256-rNTnoKSMYXe+Q4tlO2u1Gj9EOIQBsJdh+HGwT7hMyLQ=";
  };
  aarch64-linux = pkgs.fetchurl { 
     name = "aarch64-linux-nix-tools-static-sh";
     url = "${baseurl}aarch64-linux-nix-tools-static-sh.zip";
     sha256 = "sha256-R+a8d8xgh7ZUMb6VQ5tsbltN3MEVeZ2trMr9uNqA2Lw=";
  };
  x86_64-linux = pkgs.fetchurl { 
     name = "x86_64-linux-nix-tools-static-sh";
     url = "${baseurl}x86_64-linux-nix-tools-static-sh.zip";
     sha256 = "sha256-+kKP2iHrPZ/VmM3fkVGhhdWyxRdAS1l8/UpQC4sFonk=";
  };
}
