# Generated by .github/workflows/upload-artifacts-sh.yml for nix-tools-sh-0.1.0.
#
# The stable-haskell nix-tools pin, built from ./nix-tools-sh against the
# stable-haskell Cabal fork (3.17).  Separate from ./nix-tools-static.nix on
# purpose: these tools must NOT become the default for the existing GHC
# versions.  Opt in per project with haskell-nix.nix-tools-unchecked-sh; see
# overlays/default.nix.
pkgs: let baseurl = "https://github.com/input-output-hk/haskell.nix/releases/download/nix-tools-sh-0.1.0/"; in {
  aarch64-darwin = pkgs.fetchurl { 
     name = "aarch64-darwin-nix-tools-static-sh";
     url = "${baseurl}aarch64-darwin-nix-tools-static-sh.zip";
     sha256 = "sha256-seM0vhap7nUGGlvdR+5qbIgwWnJx7/BzIWpf7LI9Amg=";
  };
  x86_64-darwin = pkgs.fetchurl { 
     name = "x86_64-darwin-nix-tools-static-sh";
     url = "${baseurl}x86_64-darwin-nix-tools-static-sh.zip";
     sha256 = "sha256-/Uu0np/hJWRRaKGehsip7AgsnbWlEGsOsBndJZUQEMc=";
  };
  aarch64-linux = pkgs.fetchurl { 
     name = "aarch64-linux-nix-tools-static-sh";
     url = "${baseurl}aarch64-linux-nix-tools-static-sh.zip";
     sha256 = "sha256-FfKv2eBJ1FdoQRRJuiBbqtrXJisjtfe4a3d3xs9tshM=";
  };
  x86_64-linux = pkgs.fetchurl { 
     name = "x86_64-linux-nix-tools-static-sh";
     url = "${baseurl}x86_64-linux-nix-tools-static-sh.zip";
     sha256 = "sha256-L+GW5K2RmH4TEQZaxSVeVDl7QPKloAAdZvTOb/BcrbE=";
  };
}
