# Generated by .github/workflows/upload-artifacts-sh.yml for nix-tools-sh-0.2.3.
#
# The stable-haskell nix-tools pin, built from ./nix-tools-sh against the
# stable-haskell Cabal fork (3.17).  Separate from ./nix-tools-static.nix on
# purpose: these tools must NOT become the default for the existing GHC
# versions.  Opt in per project with haskell-nix.nix-tools-unchecked-sh; see
# overlays/default.nix.
pkgs: let baseurl = "https://github.com/input-output-hk/haskell.nix/releases/download/nix-tools-sh-0.2.3/"; in {
  aarch64-darwin = pkgs.fetchurl { 
     name = "aarch64-darwin-nix-tools-static-sh";
     url = "${baseurl}aarch64-darwin-nix-tools-static-sh.zip";
     sha256 = "sha256-fpLVq9lJHyxDCN7cGP2fIOo7iMsKo1WeLhR4RezOU+U=";
  };
  x86_64-darwin = pkgs.fetchurl { 
     name = "x86_64-darwin-nix-tools-static-sh";
     url = "${baseurl}x86_64-darwin-nix-tools-static-sh.zip";
     sha256 = "sha256-Rn1IH5Wmod9XEF7h4dCmNuzHIslbLMGeNh4ZHUDcbh0=";
  };
  aarch64-linux = pkgs.fetchurl { 
     name = "aarch64-linux-nix-tools-static-sh";
     url = "${baseurl}aarch64-linux-nix-tools-static-sh.zip";
     sha256 = "sha256-WHs/buONM5G9I0pwYMIyiZHzQQVyfTneUa3eEhXsJUI=";
  };
  x86_64-linux = pkgs.fetchurl { 
     name = "x86_64-linux-nix-tools-static-sh";
     url = "${baseurl}x86_64-linux-nix-tools-static-sh.zip";
     sha256 = "sha256-PkdRx03tN2vZOfd0ZYePJriCh3ZRW5cNnF7Oj3CAeZI=";
  };
}
