steps:
  - label: 'Run tests'
    command: "./test/tests.sh"
    agents:
      system: x86_64-linux

  - label: 'Check that jobset will evaluate in Hydra'
    command:
      - nix-build build.nix -A maintainer-scripts.check-hydra -o check-hydra.sh
      - ./check-hydra.sh
    agents:
      system: x86_64-linux

  - label: 'Check closure size'
    command:
      - nix-build build.nix -A maintainer-scripts.check-closure-size -o check-closure-size.sh
      - echo "+++ Closure size (MB)"
      - ./check-closure-size.sh
    agents:
      system: x86_64-linux

  - label: 'Update docs'
    command:
      - nix-build build.nix -A maintainer-scripts.update-docs -o update-docs.sh
      - ./update-docs.sh
    agents:
      system: x86_64-linux
