steps:
  - label: 'Run tests with ghc8104'
    command: "./test/tests.sh ghc8104"
    agents:
      system: x86_64-linux

  - label: 'Check that jobset will evaluate in Hydra'
    command:
      - nix-build build.nix -A maintainer-scripts.check-hydra -o check-hydra.sh
      - ./check-hydra.sh 0
      - ./check-hydra.sh 1
      - ./check-hydra.sh 2
      - ./check-hydra.sh 3
    agents:
      system: x86_64-linux

  - label: 'Check closure size with ghc8104'
    command:
      - nix-build build.nix -A maintainer-scripts.check-closure-size --argstr compiler-nix-name ghc8104 -o check-closure-size.sh
      - echo "+++ Closure size (MB)"
      - ./check-closure-size.sh
    agents:
      system: x86_64-linux

  - label: 'Update docs'
    command:
      - nix-build build.nix -A maintainer-scripts.update-docs -o update-docs.sh
      - ./update-docs.sh
    agents:
      system: x86_64-linux

  - label: 'Make sure materialize function does not limit concurrency'
    command:
      - nix-build build.nix -A maintainer-scripts.check-materialization-concurrency -o check-materialization-concurrency.sh
      - ./check-materialization-concurrency.sh

  - label: 'Make sure non store paths like can be used as src'
    command:
      - nix-build build.nix -A maintainer-scripts.check-path-support --argstr compiler-nix-name ghc884 -o check-path-support.sh
      - ./check-path-support.sh
