steps:
  - label: 'Update hackage.nix and stackage.nix'
    command:
      - nix-build build.nix -A maintainer-scripts.update-hackage -o update-hackage.sh
      - echo "+++ Updating hackage.nix"
      - ./update-hackage.sh
      - nix-build build.nix -A maintainer-scripts.update-stackage -o update-stackage.sh
      - echo "+++ Updating stackage.nix"
      - ./update-stackage.sh
    artifact_paths:
      - "flake.lock"
    agents:
      system: x86_64-linux

  - wait: ~
    continue_on_failure: true

  - label: 'Update pins'
    command:
      - 'buildkite-agent artifact download "flake.lock" .'
      - nix-build build.nix -A maintainer-scripts.update-pins -o update-pins.sh
      - ./update-pins.sh
    agents:
      system: x86_64-linux
