# This function cleans common build products and files not needed to do a
# haskell build from a source directory.
# This can avoid unecessary builds when these files change.
{ pkgs }: src:
  let lib = pkgs.lib;
  in if (builtins.typeOf src) == "path"
    then lib.cleanSourceWith {
      filter = with pkgs.stdenv;
        name: type: let baseName = baseNameOf (toString name); in ! (
          # Filter out cabal build products.
          baseName == "dist" || baseName == "dist-newstyle" ||
          baseName == "cabal.project.local" ||
          lib.hasPrefix ".ghc.environment" baseName ||
          # Filter out stack build products.
          lib.hasPrefix ".stack-work" baseName ||
          # Filter out files left by ghci
          lib.hasSuffix ".hi" baseName ||
          # Filter out files generated by "hasktags"
          baseName == "TAGS" || baseName == "tags" ||
          # Filter out files which are commonly edited but don't
          # affect the cabal build.
          lib.hasSuffix ".nix" baseName
        );
      src = lib.cleanSource src;
    } else src
