# pkgconfig entries to nixpkgs map
# See ../docs/dev/pkg-map.md
pkgs:
  pkgs.lib.mapAttrs (name: value: [ value ]) pkgs //
  {
    # Based on https://github.com/NixOS/cabal2nix/blob/11c68fdc79461fb74fa1dfe2217c3709168ad752/src/Distribution/Nixpkgs/Haskell/FromCabal/Name.hs#L23
    "adns"                               = [ pkgs."adns" ];
    "alsa"                               = [ pkgs."alsaLib" ];
    "alut"                               = [ pkgs."freealut" ];
    "appindicator-0.1"                   = [ pkgs."libappindicator-gtk2" ];
    "appindicator3-0.1"                  = [ pkgs."libappindicator-gtk3" ];
    "asound"                             = [ pkgs."alsaLib" ];
    "atk"                                = [ pkgs."atk" ];
    "b2"                                 = [ pkgs."libb2" ];
    "bz2"                                = [ pkgs."bzip2" ];
    "c++"                                = []; # What is that?
    "cairo-1.0"                          = [ pkgs."cairo" ];
    "cairo-gobject"                      = [ pkgs."cairo" ];
    "cairo-pdf"                          = [ pkgs."cairo" ];
    "cairo-ps"                           = [ pkgs."cairo" ];
    "cairo-svg"                          = [ pkgs."cairo" ];
    "crypt"                              = []; # provided by glibc
    "crypto"                             = [ pkgs."openssl" ];
    "curses"                             = [ pkgs."ncurses" ];
    "dbusmenu-glib-0.4"                  = [ pkgs."libdbusmenu" ];
    "dbusmenu-gtk3-0.4"                  = [ pkgs."libdbusmenu-gtk3" ]; # do we also need pkgs."gtk3"
    "dl"                                 = []; # provided by glibc
    "fftw3"                              = [ pkgs."fftw" ];
    "fftw3f"                             = [ pkgs."fftwFloat" ];
    "gconf"                              = [ pkgs."GConf" ];
    "gconf-2.0"                          = [ pkgs."GConf" ];
    "gdk-2.0"                            = [ pkgs."gtk2" ];
    "gdk-3.0"                            = [ pkgs."gtk3" ];
    "gdk-pixbuf-2.0"                     = [ pkgs."gdk_pixbuf" ];
    "gdk-x11-2.0"                        = [ pkgs."gdk_x11" ];
    "gdk-x11-3.0"                        = [ pkgs."gtk3" ];
    "gio-2.0"                            = [ pkgs."glib" ];
    "glib-2.0"                           = [ pkgs."glib" ];
    "GL"                                 = [ pkgs."libGL" ];
    "GLU"                                = [ pkgs."libGLU" pkgs."libGL" ];
    "glut"                               = [ pkgs."freeglut" pkgs."libGLU" pkgs."libGL" ];
    "gnome-keyring"                      = [ pkgs."gnome-keyring" ];
    "gnome-keyring-1"                    = [ pkgs."libgnome-keyring" ];
    "gnome-vfs-2.0"                      = [ pkgs."gnome-vfs" ];
    "gnome-vfs-module-2.0"               = [ pkgs."gnome-vfs_module" ];
    "gobject-2.0"                        = [ pkgs."glib" ];
    "gobject-introspection-1.0"          = [ pkgs."gobject-introspection" ];
    "gstreamer-audio-0.10"               = [ pkgs."gst-plugins-base" ];
    "gstreamer-audio-1.0"                = [ pkgs."gst-plugins-base" ];
    "gstreamer-base-0.10"                = [ pkgs."gst-plugins-base" ];
    "gstreamer-base-1.0"                 = [ pkgs."gst-plugins-base" ];
    "gstreamer-controller-0.10"          = [ pkgs."gstreamer" ];
    "gstreamer-dataprotocol-0.10"        = [ pkgs."gstreamer" ];
    "gstreamer-net-0.10"                 = [ pkgs."gst-plugins-base" ];
    "gstreamer-plugins-base-0.10"        = [ pkgs."gst-plugins-base" ];
    "gstreamer-video-1.0"                = [ pkgs."gst-plugins-base" ];
    "gthread-2.0"                        = [ pkgs."glib" ];
    "gtk+-2.0"                           = [ pkgs."gtk2" ];
    "gtk+-3.0"                           = [ pkgs."gtk3" ];
    "gtk-x11-2.0"                        = [ pkgs."gtk_x11" ];
    "gtksourceview-3.0"                  = [ pkgs."gtksourceview3" ];
    "hidapi-libusb"                      = [ pkgs."hidapi" ];
    "icudata"                            = [ pkgs."icu" ];
    "icui18n"                            = [ pkgs."icu" ];
    "icuuc"                              = [ pkgs."icu" ];
    "idn"                                = [ pkgs."libidn" ];
    "IL"                                 = [ pkgs."libdevil" ];
    "ImageMagick"                        = [ pkgs."imagemagick" ];
    "Imlib2"                             = [ pkgs."imlib2" ];
    "iw"                                 = [ pkgs."wirelesstools" ];
    "jack"                               = [ pkgs."libjack2" ];
    "javascriptcoregtk-3.0"              = [ pkgs."webkitgtk24x-gtk3" ]; # These are the old APIs, of which 2.4 is the last provider, so map directly to that.
    "javascriptcoregtk-4.0"              = [ pkgs."webkitgtk" ];
    "jpeg"                               = [ pkgs."libjpeg" ];
    "jvm"                                = [ pkgs."jdk" ];
    "lapack"                             = [ pkgs."liblapack" ];
    "lber"                               = [ pkgs."openldap" ];
    "ldap"                               = [ pkgs."openldap" ];
    "libavutil"                          = [ pkgs."ffmpeg" ];
    "libgsasl"                           = [ pkgs."gsasl" ];
    "libpcre"                            = [ pkgs."pcre" ];
    "libqrencode"                        = [ pkgs."qrencode" ];
    "libR"                               = [ pkgs."R" ];
    "librsvg-2.0"                        = [ pkgs."librsvg" ];
    "libsoup-2.4"                        = [ pkgs."libsoup" ];
    "libsoup-gnome-2.4"                  = [ pkgs."libsoup" ];
    "libsystemd"                         = [ pkgs."systemd" ];
    "libudev"                            = [ pkgs."systemd" ];
    "libxml-2.0"                         = [ pkgs."libxml2" ];
    "libzip"                             = [ pkgs."libzip" ];
    "libzmq"                             = [ pkgs."zeromq" ];
    "m"                                  = []; # in stdenv
    "magic"                              = [ pkgs."file" ];
    "MagickWand"                         = [ pkgs."imagemagick" ];
    "mnl"                                = [ pkgs."libmnl" ];
    "mpi"                                = [ pkgs."openmpi" ];
    "ncursesw"                           = [ pkgs."ncurses" ];
    "netsnmp"                            = [ pkgs."net_snmp" ];
    "notify"                             = [ pkgs."libnotify" ];
    "odbc"                               = [ pkgs."unixODBC" ];
    "openblas"                           = [ pkgs."openblasCompat" ];
    "panelw"                             = [ pkgs."ncurses" ];
    "pangocairo"                         = [ pkgs."pango" ];
    "pcap"                               = [ pkgs."libpcap" ];
    "pfs-1.2"                            = [ pkgs."pfstools" ];
    "png"                                = [ pkgs."libpng" ];
    "poppler-glib"                       = [ pkgs."poppler" ];
    "pq"                                 = [ pkgs."postgresql" ];
    "pthread"                            = [];
    "pulse"                              = [ pkgs."libpulseaudio" ];
    "pulse-simple"                       = [ pkgs."libpulseaudio" ];
    "python-3.3"                         = [ pkgs."python33" ];
    "python-3.4"                         = [ pkgs."python34" ];
    "Qt5Core"                            = [ pkgs."qt5" ];
    "Qt5Gui"                             = [ pkgs."qt5" ];
    "Qt5Qml"                             = [ pkgs."qt5" ];
    "Qt5Quick"                           = [ pkgs."qt5" ];
    "Qt5Widgets"                         = [ pkgs."qt5" ];
    "quadprog"                           = [ pkgs."QuadProgpp" ];
    "rt"                                 = []; # in glibc
    "rtlsdr"                             = [ pkgs."rtl-sdr" ];
    "ruby1.8"                            = [ pkgs."ruby" ];
    "sass"                               = [ pkgs."libsass" ];
    "sctp"                               = [ pkgs."lksctp-tools" ]; # This is linux-specific, we should create a common attribute if we ever add sctp support for other systems.
    "sdl2"                               = [ pkgs."SDL2" ];
    "sndfile"                            = [ pkgs."libsndfile" ];
    "sodium"                             = [ pkgs."libsodium" ];
    "sqlite3"                            = [ pkgs."sqlite" ];
    "ssh2"                               = [ pkgs."libssh2" ];
    "ssl"                                = [ pkgs."openssl" ];
    "statgrab"                           = [ pkgs."libstatgrab" ];
    "stdc++"                             = []; # What is that?
    "stdc++.dll"                         = []; # What is that?
    "systemd-journal"                    = [ pkgs."systemd" ];
    "tag_c"                              = [ pkgs."taglib" ];
    "taglib_c"                           = [ pkgs."taglib" ];
    "tensorflow"                         = [ pkgs."libtensorflow" ];
    "udev"                               = [ pkgs."systemd" ];
    "uuid"                               = [ pkgs."libossp_uuid" ];
    "vte-2.91"                           = [ pkgs."vte_291" ];
    "wayland-client"                     = [ pkgs."wayland" ];
    "wayland-cursor"                     = [ pkgs."wayland" ];
    "wayland-egl"                        = [ pkgs."libGL" ];
    "wayland-server"                     = [ pkgs."wayland" ];
    "webkit2gtk"                         = [ pkgs."webkitgtk" ];
    "webkit2gtk-4.0"                     = [ pkgs."webkitgtk" ];
    "webkit2gtk-web-extension-4.0"       = [ pkgs."webkitgtk" ];
    "webkitgtk-3.0"                      = [ pkgs."webkitgtk24x-gtk3" ]; # These are the old APIs, of which 2.4 is the last provider, so map directly to that
    "X11"                                = [ pkgs."libX11" ];
    "x11"                                = [ pkgs."xlibsWrapper" ];
    "xau"                                = [ pkgs."libXau" ];
    "Xcursor"                            = [ pkgs."libXcursor" ];
    "xerces-c"                           = [ pkgs."xercesc" ];
    "Xext"                               = [ pkgs."libXext" ];
    "xft"                                = [ pkgs."libXft" ];
    "Xi"                                 = [ pkgs."libXi" ];
    "Xinerama"                           = [ pkgs."libXinerama" ];
    "xkbcommon"                          = [ pkgs."libxkbcommon" ];
    "xml2"                               = [ pkgs."libxml2" ];
    "Xpm"                                = [ pkgs."libXpm" ];
    "Xrandr"                             = [ pkgs."libXrandr" ];
    "Xrender"                            = [ pkgs."libXrender" ];
    "Xss"                                = [ pkgs."libXScrnSaver" ];
    "Xtst"                               = [ pkgs."libXtst" ];
    "Xxf86vm"                            = [ pkgs."libXxf86vm" ];
    "yaml"                               = [ pkgs."libyaml" ];
    "yaml-0.1"                           = [ pkgs."libyaml" ];
    "z"                                  = [ pkgs."zlib" ];
    "zmq"                                = [ pkgs."zeromq" ];
}
